### ISSUE TITLE
Data is not shown on first open

### ISSUE THREAD

**Issue by keckelt** [Caleydo/tdp_dummy#15]
The first time a dummy set is clicked in Ordino, the data is not shown:

![peek 2018-08-31 15-29](https://user-images.githubusercontent.com/10337788/44915193-a6033c00-ad32-11e8-8cf6-8c3d07dadf75.gif)

**Comment by sgratzl** [comment]
why is this related to the tdp_dummy plugin and not ordino?

**Comment by CommitCrime** [comment]
I think it only happens with the dummy dataset.

**Comment by keckelt** [comment]
I think it only happens with the dummy data.

**Comment by sgratzl** [comment]
cannot reproduce: 

![open](https://user-images.githubusercontent.com/4129778/45141348-ee4caf00-b1b5-11e8-851d-c9a4c3dc3933.gif)

**Comment by keckelt** [comment]
I've used an incognito window, and the the open source ordino product.

**Comment by keckelt** [comment]
Also happened on @PatrickAdelberger's laptop after the first setup

**Comment by keckelt** [comment]
Did not happen for a while yet, neither for Patrick, nor for me.

I thought it might have to do with the missing gene/tissue/cell line data, but it is also no longer reproducible when I stop the publicdb container.

**Comment by mstreit** [comment]
Might be related to https://github.com/datavisyn/dTiles/issues/196#issuecomment-441225012
